# X,Y,Z

\begin{pmatrix}
0 & 1 \\
1 & 0
0 & 1 \\
1 & 0
1 & 0 \\
0 & 1
\end{pmatrix}

In [2]:
import numpy as np

def pauli_x():
  """Returns the Pauli X operator as a NumPy array."""
  return np.array([[0, 1], [1, 0]])

def pauli_y():
  """Returns the Pauli Y operator as a NumPy array."""
  return np.array([[0, 1], [1, 0]])

def pauli_z():
  """Returns the Pauli Z operator as a NumPy array."""
  return np.array([[1, 0], [0, 1]])

# Example usage:
x = pauli_x()
y = pauli_y()
z = pauli_z()

print(x)
print(y)
print(z)

[[0 1]
 [1 0]]
[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
