In [ ]:
pip install tensorflow

In [15]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.19.0


In [16]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [17]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.2744582 , -0.08301294, -0.07311006,  0.5019109 , -0.11030157,
         0.21008292, -0.15714422,  0.6947581 , -0.22230794, -0.5172501 ]],
      dtype=float32)

In [19]:
tf.nn.softmax(predictions).numpy()

array([[0.07138898, 0.08645196, 0.08731233, 0.15516867, 0.0841247 ,
        0.11589502, 0.08027495, 0.18817265, 0.07521073, 0.056     ]],
      dtype=float32)

In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [21]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.1550705)

In [22]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8583 - loss: 0.4873
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9542 - loss: 0.1552
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9677 - loss: 0.1087
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9735 - loss: 0.0872
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9768 - loss: 0.0741


In [24]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9785 - loss: 0.0702


[0.07016708701848984, 0.9785000085830688]

In [25]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [26]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.34086260e-08, 3.88436297e-11, 2.23748953e-06, 1.23311456e-05,
        1.73219425e-12, 1.90000932e-07, 2.70641903e-16, 9.99983311e-01,
        4.46707951e-08, 1.90993887e-06],
       [1.93583560e-06, 6.29297283e-05, 9.99913812e-01, 5.52413621e-06,
        1.06676785e-16, 1.16056412e-06, 1.13930312e-07, 2.47885696e-13,
        1.45953454e-05, 2.18462835e-12],
       [1.32658408e-06, 9.98770893e-01, 6.04630186e-05, 2.71652170e-05,
        8.59115098e-05, 1.13136011e-05, 7.53879704e-06, 8.25854775e-04,
        2.04476077e-04, 5.07829873e-06],
       [9.99965906e-01, 1.16312246e-11, 3.14360732e-05, 8.48366938e-07,
        2.62904565e-09, 1.12365819e-06, 7.19744691e-08, 4.17946779e-07,
        2.33482744e-09, 2.27192331e-07],
       [5.40589690e-06, 1.75150717e-07, 1.20730792e-05, 8.47438955e-08,
        9.96437788e-01, 3.36109025e-07, 1.33619096e-05, 2.85214483e-05,
        5.73835806e-08, 3.50224646e-03]], dtype=float32)>